import { CanvasElement } from '../types/canvas';

export function generateDiagramFromPrompt(prompt: string): CanvasElement[] {
  const p = prompt.toLowerCase();

  if (p.includes('oauth') || p.includes('auth') || p.includes('login') || p.includes('security') || p.includes('zero-trust')) {
    return [
      {
        id: 'node-client',
        type: 'rounded',
        x: 80,
        y: 220,
        width: 170,
        height: 85,
        title: 'Single Page App',
        subtitle: 'React 19 / Mobile Native',
        iconName: 'Globe',
        fillColor: '#0f172a',
        strokeColor: '#38bdf8',
        strokeWidth: 2,
        textColor: '#f8fafc',
        fontSize: 12
      },
      {
        id: 'node-idp',
        type: 'rectangle',
        x: 340,
        y: 220,
        width: 180,
        height: 85,
        title: 'OAuth 2.1 IdP',
        subtitle: 'Keycloak / Auth0 / OIDC',
        iconName: 'Shield',
        fillColor: '#1e1b4b',
        strokeColor: '#818cf8',
        strokeWidth: 2,
        textColor: '#e0e7ff',
        fontSize: 12
      },
      {
        id: 'node-apigw',
        type: 'rectangle',
        x: 610,
        y: 220,
        width: 180,
        height: 85,
        title: 'API Gateway Proxy',
        subtitle: 'Envoy Token Introspect',
        iconName: 'Server',
        fillColor: '#1c1917',
        strokeColor: '#f59e0b',
        strokeWidth: 2,
        textColor: '#fef3c7',
        fontSize: 12
      },
      {
        id: 'node-backend',
        type: 'rectangle',
        x: 880,
        y: 220,
        width: 180,
        height: 85,
        title: 'Resource Microservice',
        subtitle: 'FastAPI / Go gRPC Engine',
        iconName: 'Cpu',
        fillColor: '#064e3b',
        strokeColor: '#10b981',
        strokeWidth: 2,
        textColor: '#d1fae5',
        fontSize: 12
      },
      {
        id: 'conn-1',
        type: 'connector',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        fromId: 'node-client',
        toId: 'node-idp',
        connectorRouting: 'bezier',
        strokeColor: '#38bdf8',
        strokeWidth: 2,
        arrowEnd: 'arrow',
        text: '1. PKCE Auth Challenge'
      },
      {
        id: 'conn-2',
        type: 'connector',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        fromId: 'node-idp',
        toId: 'node-apigw',
        connectorRouting: 'bezier',
        strokeColor: '#818cf8',
        strokeWidth: 2,
        arrowEnd: 'arrow',
        text: '2. Issue Signed JWT'
      },
      {
        id: 'conn-3',
        type: 'connector',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        fromId: 'node-apigw',
        toId: 'node-backend',
        connectorRouting: 'bezier',
        strokeColor: '#10b981',
        strokeWidth: 2,
        arrowEnd: 'arrow',
        text: '3. Authorized Request'
      }
    ];
  }

  if (p.includes('data') || p.includes('cdc') || p.includes('pipeline') || p.includes('stream') || p.includes('olap')) {
    return [
      {
        id: 'node-src',
        type: 'cylinder',
        x: 80,
        y: 210,
        width: 170,
        height: 95,
        title: 'PostgreSQL OLTP',
        subtitle: 'Source Transactions',
        iconName: 'Database',
        fillColor: '#172554',
        strokeColor: '#3b82f6',
        strokeWidth: 2,
        textColor: '#dbeafe',
        fontSize: 12
      },
      {
        id: 'node-debezium',
        type: 'rectangle',
        x: 320,
        y: 215,
        width: 170,
        height: 85,
        title: 'Debezium CDC',
        subtitle: 'Log-based Change Capture',
        iconName: 'Activity',
        fillColor: '#312e81',
        strokeColor: '#a855f7',
        strokeWidth: 2,
        textColor: '#f3e8ff',
        fontSize: 12
      },
      {
        id: 'node-kafka-d',
        type: 'diamond',
        x: 560,
        y: 190,
        width: 150,
        height: 135,
        title: 'Kafka Cluster',
        subtitle: 'cdc.events.raw',
        iconName: 'Zap',
        fillColor: '#451a03',
        strokeColor: '#f97316',
        strokeWidth: 2,
        textColor: '#ffedd5',
        fontSize: 12
      },
      {
        id: 'node-flink',
        type: 'rectangle',
        x: 780,
        y: 215,
        width: 170,
        height: 85,
        title: 'Apache Flink',
        subtitle: 'Stream Aggregation & Windowing',
        iconName: 'Cpu',
        fillColor: '#064e3b',
        strokeColor: '#10b981',
        strokeWidth: 2,
        textColor: '#d1fae5',
        fontSize: 12
      },
      {
        id: 'node-clickhouse',
        type: 'cylinder',
        x: 1020,
        y: 210,
        width: 180,
        height: 95,
        title: 'ClickHouse OLAP',
        subtitle: 'Real-Time Columnar DB',
        iconName: 'Database',
        fillColor: '#1e1b4b',
        strokeColor: '#818cf8',
        strokeWidth: 2,
        textColor: '#e0e7ff',
        fontSize: 12
      },
      {
        id: 'conn-d1',
        type: 'connector',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        fromId: 'node-src',
        toId: 'node-debezium',
        connectorRouting: 'bezier',
        strokeColor: '#3b82f6',
        strokeWidth: 2,
        arrowEnd: 'arrow',
        text: 'WAL Stream'
      },
      {
        id: 'conn-d2',
        type: 'connector',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        fromId: 'node-debezium',
        toId: 'node-kafka-d',
        connectorRouting: 'bezier',
        strokeColor: '#a855f7',
        strokeWidth: 2,
        arrowEnd: 'arrow'
      },
      {
        id: 'conn-d3',
        type: 'connector',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        fromId: 'node-kafka-d',
        toId: 'node-flink',
        connectorRouting: 'bezier',
        strokeColor: '#f97316',
        strokeWidth: 2,
        arrowEnd: 'arrow'
      },
      {
        id: 'conn-d4',
        type: 'connector',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        fromId: 'node-flink',
        toId: 'node-clickhouse',
        connectorRouting: 'bezier',
        strokeColor: '#10b981',
        strokeWidth: 2,
        arrowEnd: 'arrow',
        text: 'Batch Insert'
      }
    ];
  }

  return [
    {
      id: 'node-gen-1',
      type: 'cloud',
      x: 80,
      y: 220,
      width: 170,
      height: 90,
      title: 'Global API Gateway',
      subtitle: 'Edge Routing & TLS',
      iconName: 'Cloud',
      fillColor: '#0f172a',
      strokeColor: '#38bdf8',
      strokeWidth: 2,
      textColor: '#f8fafc',
      fontSize: 12
    },
    {
      id: 'node-gen-2',
      type: 'rectangle',
      x: 320,
      y: 220,
      width: 180,
      height: 90,
      title: 'Orchestrator Service',
      subtitle: 'DAG State Machine',
      iconName: 'Workflow',
      fillColor: '#1e1b4b',
      strokeColor: '#818cf8',
      strokeWidth: 2,
      textColor: '#e0e7ff',
      fontSize: 12
    },
    {
      id: 'node-gen-3',
      type: 'diamond',
      x: 580,
      y: 195,
      width: 150,
      height: 140,
      title: 'Event Router',
      subtitle: 'Pub/Sub Broker',
      iconName: 'Activity',
      fillColor: '#451a03',
      strokeColor: '#f97316',
      strokeWidth: 2,
      textColor: '#ffedd5',
      fontSize: 12
    },
    {
      id: 'node-gen-4',
      type: 'rectangle',
      x: 810,
      y: 220,
      width: 180,
      height: 90,
      title: 'AI Inference Worker',
      subtitle: 'GPU Cluster / vLLM',
      iconName: 'Cpu',
      fillColor: '#064e3b',
      strokeColor: '#10b981',
      strokeWidth: 2,
      textColor: '#d1fae5',
      fontSize: 12
    },
    {
      id: 'node-gen-5',
      type: 'cylinder',
      x: 1060,
      y: 220,
      width: 170,
      height: 90,
      title: 'State Store',
      subtitle: 'Distributed KV & DB',
      iconName: 'Database',
      fillColor: '#172554',
      strokeColor: '#60a5fa',
      strokeWidth: 2,
      textColor: '#dbeafe',
      fontSize: 12
    },
    {
      id: 'conn-g1',
      type: 'connector',
      x: 0,
      y: 0,
      width: 0,
      height: 0,
      fromId: 'node-gen-1',
      toId: 'node-gen-2',
      connectorRouting: 'bezier',
      strokeColor: '#38bdf8',
      strokeWidth: 2,
      arrowEnd: 'arrow'
    },
    {
      id: 'conn-g2',
      type: 'connector',
      x: 0,
      y: 0,
      width: 0,
      height: 0,
      fromId: 'node-gen-2',
      toId: 'node-gen-3',
      connectorRouting: 'bezier',
      strokeColor: '#818cf8',
      strokeWidth: 2,
      arrowEnd: 'arrow'
    },
    {
      id: 'conn-g3',
      type: 'connector',
      x: 0,
      y: 0,
      width: 0,
      height: 0,
      fromId: 'node-gen-3',
      toId: 'node-gen-4',
      connectorRouting: 'bezier',
      strokeColor: '#f97316',
      strokeWidth: 2,
      arrowEnd: 'arrow'
    },
    {
      id: 'conn-g4',
      type: 'connector',
      x: 0,
      y: 0,
      width: 0,
      height: 0,
      fromId: 'node-gen-4',
      toId: 'node-gen-5',
      connectorRouting: 'bezier',
      strokeColor: '#10b981',
      strokeWidth: 2,
      arrowEnd: 'arrow'
    }
  ];
}
